/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vente;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HACKER
 */
public class Login extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
     
    public Login() {
        initComponents();
        icone();
        
    }
    public void connect(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/stock","root","");
            System.out.println("connection reussie");
            
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
    }
    private void icone() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/Vente/IMG/Blue Minimalist Letter D Logo_20240521_200331_0000.jpg"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        mdp = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        entete = new javax.swing.JLabel();
        nom1 = new javax.swing.JTextField();
        tet = new javax.swing.JLabel();
        envoyer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FOUR A'S Center Market");
        setBackground(new java.awt.Color(0, 255, 0));
        setBounds(new java.awt.Rectangle(10, 10, 10, 10));
        setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 51));
        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenue dans  votre Center Market");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Page de connexion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 520, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setText("Mot De Passe");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 50));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 204));
        jLabel5.setText("Nom D'utilisateur");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, 50));

        nom.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 0, 0));
        nom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0), 3));
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 360, 40));

        mdp.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        mdp.setForeground(new java.awt.Color(255, 0, 0));
        mdp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0), 3));
        getContentPane().add(mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 360, 40));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 204));
        jButton1.setText("Connexion");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 240, 50));

        entete.setBackground(new java.awt.Color(153, 255, 0));
        entete.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        entete.setForeground(new java.awt.Color(51, 0, 204));
        entete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entete.setText("Contactez L'Admin Pour Modifier votre Mot de Passe");
        entete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(entete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 490, 40));

        nom1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        nom1.setForeground(new java.awt.Color(255, 0, 0));
        nom1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0), 3));
        nom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom1ActionPerformed(evt);
            }
        });
        getContentPane().add(nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 360, 40));

        tet.setBackground(new java.awt.Color(153, 255, 0));
        tet.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        tet.setForeground(new java.awt.Color(51, 0, 204));
        tet.setText("Nom D'utilisateur");
        tet.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(tet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 190, 50));

        envoyer.setBackground(new java.awt.Color(153, 255, 153));
        envoyer.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        envoyer.setForeground(new java.awt.Color(51, 0, 204));
        envoyer.setText("Envoyer");
        envoyer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        envoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyerActionPerformed(evt);
            }
        });
        getContentPane().add(envoyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 240, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vente/IMG/Blue Minimalist Letter D Logo_20240521_200331_0000.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 570, 560));

        setSize(new java.awt.Dimension(579, 583));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nomv =nom.getText().toString() ;
        String pwd = mdp.getText().toString();
        try{
            connect();
            pst = con.prepareStatement("SELECT * FROM users WHERE nom =? AND  mdp =?");
            pst.setString(1,nomv);
            pst.setString(2, pwd);
            rs = pst.executeQuery();
            if(nomv.isEmpty() || pwd.isEmpty()){
                JOptionPane.showMessageDialog(null, "Veuillez Remplir Tous les Champs !!! ");
            }
            else if(rs.next()){
                
                    Login.super.dispose();
                    Notification av = new Notification();
                    av.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Bienvenue "+nomv);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Identifiant incorrects");
                nom.setText("");
                mdp.setText("");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom1ActionPerformed

    private void envoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyerActionPerformed
        String no = nom1.getText().toString();
        connect();
        
        try{
            if(no.isEmpty()){
                JOptionPane.showMessageDialog(null, "Veuillez mettre votre Nom d'Utilisateur");
            }
            else{
            pst=con.prepareStatement("INSERT INTO oublie (motif,nomu) VALUES ('mot de passe oublier',?)");
            pst.setString(1,no);
            JOptionPane.showMessageDialog(null, "votre requete a été enrégistré");
            pst.executeUpdate();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_envoyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel entete;
    private javax.swing.JButton envoyer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField mdp;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nom1;
    private javax.swing.JLabel tet;
    // End of variables declaration//GEN-END:variables
}
