/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vente;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HACKER
 */
public class Stock extends javax.swing.JFrame {

    
        Connection con;
    PreparedStatement pst;
    ResultSet rs;
      public void connect(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/stock","root","");
            System.out.println("connection reussie");
            
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
    }
      public void stock(){
           String [] entete={"Article","Description","Quantite En Stock","Statut"};
      String [] montere = new String[4];
      DefaultTableModel model = new DefaultTableModel(null,entete);
        try{
            connect();
            String req = "SELECT article, description, stock\n" +
"FROM vente \n" +
"WHERE (article, description, date_vente) IN (\n" +
"    SELECT article, description, MAX(date_vente)\n" +
"    FROM vente\n" +
"    GROUP BY article, description\n" +
")";
            Statement st = con.createStatement();
        rs= st.executeQuery(req);
        while(rs.next()){
         montere [0]=rs.getString("article");
            montere [1]=rs.getString("description");
            montere [2]=rs.getString("stock");
            String gt = rs.getString("stock");
            int as = Integer.parseInt(gt);
            if(as <=20){
                montere[3]="Stock critique atteint";
            }
            else{
                montere[3]="Article en stock";
            }
            model.addRow(montere);
            
        }
        jTable1.setModel(model);
        con.close();    
        
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
      }
    public Stock() {
        initComponents();
        connect();
        stock();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        article = new javax.swing.JTextField();
        refference = new javax.swing.JTextField();
        prix_unitaire = new javax.swing.JTextField();
        prix_total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        nature = new javax.swing.JComboBox<>();
        quantite = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prix_Total");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 170, 40));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(102, 255, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 880, 200));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenue Dans Votre Center Market!!! Verifier Vos Stocks Ici");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 630, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Passez Vos Commandes ici!!!");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 630, 40));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nom  Fournisseur");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 190, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Paiement");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 140, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Description");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 140, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Prix_Unitaire");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 170, 40));

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Quantite");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 140, 40));

        date.setEditable(false);
        date.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        date.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(102, 255, 0), new java.awt.Color(255, 255, 0)));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 300, 40));

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Article");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 170, 40));

        nom.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        nom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(102, 255, 0), new java.awt.Color(255, 255, 0)));
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 300, 40));

        article.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        article.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(102, 255, 0), new java.awt.Color(255, 255, 0)));
        getContentPane().add(article, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 300, 40));

        refference.setEditable(false);
        refference.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        refference.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(102, 255, 0), new java.awt.Color(255, 255, 0)));
        getContentPane().add(refference, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 300, 40));

        prix_unitaire.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        prix_unitaire.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(102, 255, 0), new java.awt.Color(255, 255, 0)));
        getContentPane().add(prix_unitaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 300, 40));

        prix_total.setEditable(false);
        prix_total.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        prix_total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(102, 255, 0), new java.awt.Color(255, 255, 0)));
        getContentPane().add(prix_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 300, 40));

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Telephone");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 140, 40));

        jLabel11.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Refference");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 40));

        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Date");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 255, 0)));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 140, 40));

        telephone.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        telephone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(102, 255, 0), new java.awt.Color(255, 255, 0)));
        getContentPane().add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 300, 40));

        description.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        description.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(102, 255, 0), new java.awt.Color(255, 255, 0)));
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 300, 40));

        nature.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espece", "Orange Monney", "MTN MOMO", "Cheque Bancaire", "Credit" }));
        getContentPane().add(nature, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 300, 40));

        quantite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantiteStateChanged(evt);
            }
        });
        getContentPane().add(quantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 300, 40));

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 0));
        jButton1.setText("Payer");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 300, 40));

        jButton2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 255, 0));
        jButton2.setText("Valider Commande");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 300, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vente/IMG/00000002.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 520, 350));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vente/IMG/00000002.jpg"))); // NOI18N
        jLabel14.setText("jLabel13");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 276, 530, 420));

        jButton3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 255, 0));
        jButton3.setText("Payer");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 300, 40));

        jButton4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 255, 0));
        jButton4.setText("Payer");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 300, 40));

        jButton5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 255, 0));
        jButton5.setText("Acceuil");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        setSize(new java.awt.Dimension(1010, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String mat(){
      String code = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
     StringBuilder ma = new StringBuilder();
      Random sr = new Random();
     for(int i=0;i<=10;i++){
         ma.append(code.charAt(sr.nextInt(code.length())));
    
     }
     
     
     return ma.toString();
     
 }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
        String ng  = nom.getText();
    String tel = telephone.getText();
    String art =article.getText();
    String desc = description.getText();
    String pu = prix_unitaire.getText();
    String pt = prix_total.getText();
    refference.setText(mat());
    String ref = refference.getText();
    int qte = (int) quantite.getValue();
    String va = String.valueOf(qte);
    String na = nature.getSelectedItem().toString();
    date.setText(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
    String da = date.getText();
    if(ng.isEmpty()||tel.isEmpty()||art.isEmpty()||desc.isEmpty()||pu.isEmpty()||pt.isEmpty()||ref.isEmpty()){
        JOptionPane.showMessageDialog(null, "Veuillez remplir tous le champs");
    }
    else{
        connect();
        
        pst=con.prepareStatement("INSERT INTO commande(nom,telephone,refference,article,description,pu,qte,pt,nature) VALUES (?,?,?,?,?,?,?,?,?)");
            pst.setString(1,ng);
            pst.setString(2,tel);
            pst.setString(3,ref);
             pst.setString(4,art);
            pst.setString(5,desc);
            pst.setString(6,pu);
             pst.setString(7,va);
            pst.setString(8,pt);
            pst.setString(9,na); 
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ajout Effectué avec succès");
            con.close();
           
    }
        
    }catch(Exception e){
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void quantiteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantiteStateChanged
         int pr = Integer.parseInt(prix_unitaire.getText());
				int qt =(int) quantite.getValue();
				int to = pr * qt;
				prix_total.setText(String.valueOf(to));
    }//GEN-LAST:event_quantiteStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Stock.super.dispose();
        Notification an  = new Notification ();
        an.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField article;
    private javax.swing.JTextField date;
    private javax.swing.JTextField description;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> nature;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prix_total;
    private javax.swing.JTextField prix_unitaire;
    private javax.swing.JSpinner quantite;
    private javax.swing.JTextField refference;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables
}
